apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-hello-world
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-hello-world
  template: 
    metadata:
      labels:
        app: go-hello-world
    spec:
      containers:
      - name: go-hello-world
        image: alsidneio/go-hello-world:1.0.0
        imagePullPolicy: IfNotPresent
        ports:         
          - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
            httpHeaders:
              - name: Accept
                value: application/json
          initialDelaySeconds: 15
          periodSeconds: 36
          timeoutSeconds: 12
        readinessProbe: 
          httpGet:
            path: /readiness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 15
          timeoutSeconds: 5
        

  